import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import {
  requireShareHtmlPath,
  requireWorkbenchHtmlPath,
  resolveShareHtmlPath,
  resolveWorkbenchHtmlPath,
} from './spaHtmlPaths.ts';

const root = path.resolve(import.meta.dirname, '..');

const desktopHtml = readFileSync(path.resolve(root, 'dist/desktop/index.html'), 'utf8');

/* 2026-09-17：移动版构建整体删除——模板只生成 desktop，mobileHtmlTemplate 不再存在。 */
const output = `// Auto-generated by scripts/generateSpaTemplates.mts after vite build
// Do not edit manually

export const desktopHtmlTemplate = ${JSON.stringify(desktopHtml)};
`;

writeFileSync(
  path.resolve(root, 'src/app/spa/[variants]/[[...path]]/spaHtmlTemplates.ts'),
  output,
  'utf8',
);

console.log('Generated spaHtmlTemplates.ts (desktop only)');

const authHtmlPath = path.resolve(root, 'dist/auth/index.auth.html');

if (existsSync(authHtmlPath)) {
  const authHtml = readFileSync(authHtmlPath, 'utf8');

  const authOutput = `// Auto-generated by scripts/generateSpaTemplates.mts after vite build
// Do not edit manually

export const authHtmlTemplate = ${JSON.stringify(authHtml)};
`;

  writeFileSync(path.resolve(root, 'src/app/spa-auth/authHtmlTemplate.ts'), authOutput, 'utf8');

  console.log('Generated authHtmlTemplate.ts');
} else {
  console.log('Skipped authHtmlTemplate.ts (no dist/auth build)');
}

const resolvedWorkbenchHtmlPath =
  process.env.WORKBENCH_REQUIRED === '1'
    ? requireWorkbenchHtmlPath(root)
    : resolveWorkbenchHtmlPath(root);

if (resolvedWorkbenchHtmlPath) {
  const workbenchHtml = readFileSync(resolvedWorkbenchHtmlPath, 'utf8');

  const workbenchOutput = `// Auto-generated by scripts/generateSpaTemplates.mts after vite build
// Do not edit manually

export const workbenchHtmlTemplate = ${JSON.stringify(workbenchHtml)};
`;

  writeFileSync(
    path.resolve(root, 'src/app/spa-workbench/workbenchHtmlTemplate.ts'),
    workbenchOutput,
    'utf8',
  );

  console.log('Generated workbenchHtmlTemplate.ts');
} else {
  console.log('Skipped workbenchHtmlTemplate.ts (no dist/workbench build)');
}

const resolvedShareHtmlPath =
  process.env.SHARE_REQUIRED === '1' ? requireShareHtmlPath(root) : resolveShareHtmlPath(root);

if (resolvedShareHtmlPath) {
  const shareHtml = readFileSync(resolvedShareHtmlPath, 'utf8');

  const shareOutput = `// Auto-generated by scripts/generateSpaTemplates.mts after vite build
// Do not edit manually

export const shareHtmlTemplate = ${JSON.stringify(shareHtml)};
`;

  writeFileSync(path.resolve(root, 'src/app/spa-share/shareHtmlTemplate.ts'), shareOutput, 'utf8');

  console.log('Generated shareHtmlTemplate.ts');
} else {
  console.log('Skipped shareHtmlTemplate.ts (no dist/share build)');
}
